### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title":"Our second post",
  "content":"The second post",
  "owner":"yoni isakov"
}

### Get all posts
GET http://localhost:3000/posts

### Get a specific post by ID
GET http://localhost:3000/posts/673cdbf4c0bc0c39cdc7d479

### Get post by owner
GET http://localhost:3000/posts?owner=yoni

### Update a post
PUT http://localhost:3000/posts/673cd3d3c9ea72dc2808df5b
Content-Type: application/json

{
  "title":"Updated Post",
  "content":"Update",
  "owner":"yoni isakov"
}


### Create a Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "673cd3d3c9ea72dc2808df59", 
  "content": "This is a test comment.",
  "author": "Test1"
}


### Get Comments
GET  http://localhost:3000/comments

### Get Comments By Auth
GET  http://localhost:3000/comments/by-author?author=Test1

### Get Comments ById
GET  http://localhost:3000/comments/673dcec87ecb88c75a5183b0

### Get Comments ByPostId
GET  http://localhost:3000/comments/by-post/673cd3d3c9ea72dc2808df5c

### delete Comments ById
DELETE   http://localhost:3000/comments/6748b743e4aa09486e927dc8

### update Comments ById
PUT   http://localhost:3000/comments/673dcec87ecb88c75a5183b0
Content-Type: application/json

{            
  "postId": "673cd3d3c9ea72dc2808df5c", 
  "content": "This is a test comment.",
  "author": "Test"
}