### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title":"Our second post",
  "content":"The second post",
  "owner":"yoni isakov"
}

### Get all posts
GET http://localhost:3000/posts

### Get a specific post by ID
GET http://localhost:3000/posts/673cd423c9ea72dc2808df5e

### Get post by owner
GET http://localhost:3000/posts?owner=yoni