### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title":"Our second post",
  "content":"The second post",
  "owner":"yoni isakov"
}

### Get all posts
GET http://localhost:3000/posts

### Get a specific post by ID
GET http://localhost:3000/posts/673cdbf4c0bc0c39cdc7d479

### Get post by owner
GET http://localhost:3000/posts?owner=yoni

### Update a post
PUT http://localhost:3000/posts/673cd3d3c9ea72dc2808df5c
Content-Type: application/json

{
  "title":"Updated Post",
  "content":"Update",
  "owner":"yoni isakov"
}


### Create a Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "673cd3d3c9ea72dc2808df5c", 
  "content": "This is a test comment.",
  "author": "Test"
}


### Get Comments
GET  http://localhost:3000/comments

### Get Comments ById
GET  http://localhost:3000/comments/673db30e3261ef4643e3e4af

### Get Comments ByPostId
GET  http://localhost:3000/comments?postId=673cd3d3c9ea72dc2808df5c