### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title":"Our test post",
  "content":"The test post",
  "owner":"test2"
}

### Get all posts
GET http://localhost:3000/posts

### Get a specific post by ID
GET http://localhost:3000/posts/6748bc45ae462904a9a87866

### Get post by owner
GET http://localhost:3000/posts?owner=test2

### Update a post
PUT http://localhost:3000/posts/6748bc45ae462904a9a87866
Content-Type: application/json

{
  "title":"Updated Post",
  "content":"Update",
  "owner":"yoni isakov"
}

### Delete a post by ID
DELETE http://localhost:3000/posts/6748bc51ae462904a9a87869

### Delete all posts
DELETE http://localhost:3000/posts

### Create a Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "6748bc90ae462904a9a87875", 
  "content": "This is a test comment.",
  "author": "Test2"
}


### Get Comments
GET  http://localhost:3000/comments

### Get Comments By Auth
GET  http://localhost:3000/comments/by-author?author=Test1

### Get Comments ById
GET  http://localhost:3000/comments/6748bc9fae462904a9a87878

### Get Comments ByPostId
GET  http://localhost:3000/comments/by-post/6748bc90ae462904a9a87875

### delete Comments ById
DELETE   http://localhost:3000/comments/6748bc9fae462904a9a87878

### update Comments ById
PUT   http://localhost:3000/comments/6748bafd027aa7d8d7496eb2
Content-Type: application/json

{            
  "postId": "6748bc90ae462904a9a87875", 
  "content": "This is a test comment update",
  "author": "Test update"
}